### ISSUE TITLE
Invalid Country Code

### ISSUE THREAD

**Issue by ls-milkyway** [jgomez177/plex-for-channels#4]
According to your read-me `-e PLEX_CODE=local[,us_west]` outputs invalid country code..How to include multiple countries in docker run ...please correct your read-me 

`docker run -d --restart unless-stopped --network=host -e PLEX_PORT=[your_port_number_here] -e PLEX_CODE=local[,us_west,etc.] --name  plex-for-channels ghcr.io/jgomez177/plex-for-channels`

is not working ..instead `-p [your_port_number_here]:7777` is working.

**Comment by jgomez177** [comment]
there is not an issue with the read-me
The braces indicate an option for configuration depending on how the user want to configure the container

this is dependant on how many optional settings you are wanting to use
` -e PLEX_CODE=local` is for local only
` -e PLEX_CODE=local,us_west` is for local and US West
` -e PLEX_CODE=us_east,uk` is for US east and UK only

**Comment by ls-milkyway** [comment]
Actually list population takes lot of time ...specially if  -e PLEX_CODE= has lot of options.
